databases:
  - name: postgres
    ipAllowList: []
    databaseName: search_engine_561u
    user: kedro

services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
